In [2]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [3]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [16]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-05-19 17:32:51.516267
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-05-19 17:32:51.516267
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-05-19 17:32:51.516267

In [17]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,	
         MAKTX VARCHAR,
         WERKS VARCHAR,
         MAINS VARCHAR,
         LABST VARCHAR,
        nome_arquivo VARCHAR,	
        data_ingestao TIMESTAMP   
    )
""")

In [18]:
con.execute(" INSERT INTO bronze_produtos SELECT * FROM df")

In [22]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-05-19 17:22:32.384488
1  10002   MARTELO  BT50   100   500  z0019_1.csv 2026-05-19 17:22:32.384488
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-05-19 17:22:32.384488
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-05-19 17:32:51.516267
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-05-19 17:32:51.516267
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-05-19 17:32:51.516267

In [21]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [23]:
con.close()